### ISSUE TITLE
[BUG] PredicateToSQL

### ISSUE THREAD

**Issue by sawcioo** [dkharrat/NexusData#6]
Hello, i create predicate like this:
`PredicateBuilder.parse("createDate != null")`.
I gets `java.lang.NullPointerException
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService$QueryBuilder.visit(PredicateToSQL.java:85)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService$QueryBuilder.visit(PredicateToSQL.java:166)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService$QueryBuilder.visit(PredicateToSQL.java:137)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService$QueryBuilder.visit(PredicateToSQL.java:156)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService$QueryBuilder.visit(PredicateToSQL.java:116)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService$QueryBuilder.visit(PredicateToSQL.java:154)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService.buildQuery(PredicateToSQL.java:62)
            at com.github.dkharrat.nexusdata.store.DatabaseQueryService.query(PredicateToSQL.java:41)
            at com.github.dkharrat.nexusdata.store.AndroidSqlPersistentStore.executeFetchRequest(AndroidSqlPersistentStore.java:85)
            at com.github.dkharrat.nexusdata.core.ObjectContext.executeFetchOperation(ObjectContext.java:120)`

**Comment by dkharrat** [comment]
Pushed release 0.1.3 containing this fix.
